apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - proxy.yaml
  - apidoc.yaml
secretGenerator:
  - name: todo-db-credentials
    literals:
      - PGDATABASE=todo
      - PGHOST=postgres
      - PGUSER=todo
      - PGSSLMODE=disable
patchesStrategicMerge:
  - todo.yaml
