apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: todo-app-skaffold
build:
  artifacts:
    - image: goose
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        dependencies:
          paths:
            - pkg/**
            - cmd/goose/**
        env:
          - GOOGLE_RUNTIME_VERSION=1.15.3
          - GOOGLE_BUILDABLE=./cmd/goose
          - GOOGLE_CLEAR_SOURCE=true
      sync:
        auto: true
    - image: todo
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        dependencies:
          paths:
            - pkg/**
            - services/todo/**
        env:
          - GOOGLE_RUNTIME_VERSION=1.15.3
          - GOOGLE_BUILDABLE=./services/todo
          - GOOGLE_CLEAR_SOURCE=true
      sync:
        auto: true
    - image: redoc
      docker:
        dockerfile: api/Dockerfile
deploy:
  statusCheckDeadlineSeconds: 300
profiles:
  - name: local
    activation:
      - kubeContext: kind-local
      - command: dev
      - command: run
    deploy:
      kubeContext: kind-local
      kustomize:
        paths:
          - ops/overlays/dev
    portForward:
      - resourceType: service
        resourceName: todo
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: redoc
        port: 80
        localPort: 9000
      - resourceType: service
        resourceName: postgres
        port: 5432
