apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: todo-app-skaffold
build:
  artifacts:
    - image: todo
      docker:
        dockerfile: services/todo/Dockerfile
      sync:
        infer: []
    - image: goose
      docker:
        dockerfile: cmd/goose/Dockerfile
    - image: apidoc
      docker:
        dockerfile: api/Dockerfile
  local:
    useBuildkit: true
deploy:
  statusCheckDeadlineSeconds: 300
portForward:
  - resourceType: service
    resourceName: todo
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: apidoc
    port: 80
    localPort: 9000
  - resourceType: service
    resourceName: postgres
    port: 5432
profiles:
  - name: local
    activation:
      - command: run
      - command: dev
      - command: debug
    deploy:
      kubeContext: kind-local
      kustomize:
        paths:
          - ops/overlays/local
  - name: build-dev
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: services/todo/Dockerfile.dev
