FROM golang:1.15.3
RUN apt-get -qq update && apt-get -q -y install xz-utils
ARG WATCHEXEC_VERSION=1.14.1
RUN curl -sSfL https://github.com/watchexec/watchexec/releases/download/${WATCHEXEC_VERSION}/watchexec-${WATCHEXEC_VERSION}-x86_64-unknown-linux-gnu.tar.xz | \
    tar -C /usr/local/bin --strip-components 1 -xJ watchexec-${WATCHEXEC_VERSION}-x86_64-unknown-linux-gnu/watchexec && \
	chmod u+x /usr/local/bin/watchexec 
WORKDIR /opt/build
COPY go.mod go.sum ./
RUN go mod download
COPY pkg pkg
COPY services/todo services/todo
CMD watchexec -r -- go run ./services/todo