FROM golang:1.17.1-buster AS builder
# install xz required to uncompress watchexec
RUN apt-get -qq update && \
    apt-get -q -y install xz-utils && \
    rm -rf /var/lib/apt/lists/*
# install watchexec
ARG WATCHEXEC_VERSION=1.14.1
RUN curl -sSfL https://github.com/watchexec/watchexec/releases/download/${WATCHEXEC_VERSION}/watchexec-${WATCHEXEC_VERSION}-x86_64-unknown-linux-gnu.tar.xz | \
    tar -C /usr/local/bin --strip-components 1 -xJ watchexec-${WATCHEXEC_VERSION}-x86_64-unknown-linux-gnu/watchexec && \
	chmod u+x /usr/local/bin/watchexec 
# copy source files
WORKDIR /opt/build
COPY go.* .
COPY cmd/todo-service cmd/todo-service
COPY api api
COPY internal internal
COPY services/todo services/todo
# download dependencies
RUN go get ./cmd/todo-service
# restart service on file changes
CMD watchexec -r -- go run ./cmd/todo-service