apiVersion: v1
kind: Service
metadata:
  name: apidoc
spec:
  selector:
    app: apidoc
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidoc
  labels:
    app: apidoc
spec:
  selector:
    matchLabels:
      app: apidoc
  template:
    metadata:
      labels:
        app: apidoc
    spec:
      containers:
        - name: apidoc
          image: apidoc
