/*
 * Todo API
 *
 * Todo API
 *
 * API version: 0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package todo

import (
	"encoding/json"
)

// CreateTodoRequest struct for CreateTodoRequest
type CreateTodoRequest struct {
	Title string `json:"title"`
	Content string `json:"content"`
}

// NewCreateTodoRequest instantiates a new CreateTodoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTodoRequest(title string, content string, ) *CreateTodoRequest {
	this := CreateTodoRequest{}
	this.Title = title
	this.Content = content
	return &this
}

// NewCreateTodoRequestWithDefaults instantiates a new CreateTodoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTodoRequestWithDefaults() *CreateTodoRequest {
	this := CreateTodoRequest{}
	return &this
}

// GetTitle returns the Title field value
func (o *CreateTodoRequest) GetTitle() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreateTodoRequest) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreateTodoRequest) SetTitle(v string) {
	o.Title = v
}

// GetContent returns the Content field value
func (o *CreateTodoRequest) GetContent() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateTodoRequest) GetContentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateTodoRequest) SetContent(v string) {
	o.Content = v
}

func (o CreateTodoRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["content"] = o.Content
	}
	return json.Marshal(toSerialize)
}

type NullableCreateTodoRequest struct {
	value *CreateTodoRequest
	isSet bool
}

func (v NullableCreateTodoRequest) Get() *CreateTodoRequest {
	return v.value
}

func (v *NullableCreateTodoRequest) Set(val *CreateTodoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTodoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTodoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTodoRequest(val *CreateTodoRequest) *NullableCreateTodoRequest {
	return &NullableCreateTodoRequest{value: val, isSet: true}
}

func (v NullableCreateTodoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTodoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
