#!/bin/bash
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
DOCKER_RUN_OPTIONS="${OPTIONS:-} -e JAVA_OPTS=-Dlog.level=error --rm --workdir $PWD"
IMAGE="openapitools/openapi-generator-cli:v${OPENAPIGENERATORCLI_VERSION:-4.3.1}"

# Only allocate tty if we detect one
if [ -t 1 ]; then
    DOCKER_RUN_OPTIONS+=" --tty"
elif [ -t 0 ]; then
    DOCKER_RUN_OPTIONS+=" --interactive"
fi

# Setup volume mounts
if [ "$DIR" != '/' ]; then
    DOCKER_RUN_OPTIONS+=" --volume $DIR:$DIR"
fi

# shellcheck disable=SC2086
exec docker run $DOCKER_RUN_OPTIONS $IMAGE "$@"
