name: Skaffold Todo App
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.17"
          - "1.16"
    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            bin/
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum', 'Makefile') }}
      - name: Download dependencies
        run: make deps
      - name: Ensure code is formatted
        run: make format && make git-dirty
      - name: Lint
        run: GOLANGCILINT_CONCURRENCY=4 make lint
      - name: Unit test with coverage
        run: make test-coverage
      - name: Integration test
        run: make integration-test
